git config --global credential.helper 'cache --timeout=2628000'

* ~/suckless/dwm/

setup — if you’ve done this kind of thing before or	
HTTPS
SSH
https://github.com/sunyta2/dwm.git
Get started by creating a new file or uploading an existing file. We recommend every repository include a README, LICENSE, and .gitignore.

#+BEGIN_SRC sh
git clone https://github.com/sunyta2/config_github.git
# …or create a new repository on the command line
echo "* dwm" >> readme.org
git init
git add README.md
git commit -m "first commit"
git remote add origin https://github.com/sunyta2/dwm.git
git push -u origin master
#+END_SRC

#+BEGIN_SRC sh
#…or push an existing repository from the command line
git remote add origin https://github.com/sunyta2/dwm.git
git push -u origin master
#+END_SRC

…or import code from another repository
You can initialize this repository with code from a Subversion, Mercurial, or TFS project.


lrwxr-xr-x  1 thinkpad  admin  27  6 18 10:24 /usr/local/bin/dwm -> ../Cellar/dwm/6.2_1/bin/dwm
 which dwm in macosx
$ brew install freetype --with-freetype-dir=/usr/local/Cellar/freetype
"Error: invalid option: --with-freetype-dir=/usr/local/Cellar/freetype" – Marc J. Schmidt Oct 16 at 12:54
add a comment

Add the path to your headers to the clang include paths by using -I parameter: clang++ ... -I/opt/local/include ... for example.
Next you'll probably get link errors - use -L parameter.


How add rsa_key in arco
pub키를 일단 추가해서 실험함
